- model: config.FeatureLocation
  pk: 1
  fields:
    type: ios
    location: libraries/ios

- model: config.FeatureLocation
  pk: 2
  fields:
    type: android
    location: libraries/android

- model: config.FeatureLocation
  pk: 3
  fields:
    type: web
    location: libraries/web